name: ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install docker client
        run: |
          #!/bin/sh

          wget -O docker.tgz -q https://download.docker.com/linux/static/stable/x86_64/docker-23.0.4.tgz
          tar xzf docker.tgz
          mv docker/* /usr/local/bin
          rmdir docker
          echo DOCKER_REGISTRY_URL=${GITHUB_SERVER_URL##*/} >> ${GITHUB_ENV}
      -
        name: Login to Gitea registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: code.devcloud.soren.tools
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          push: true
          tags: code.devcloud.soren.tools/platform/caddy:latest
          sbom: true
          provenance: true
