name: ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install docker client
        run: |
          #!/bin/sh
          wget -O docker.tgz -q https://download.docker.com/linux/static/stable/x86_64/docker-24.0.2.tgz
          tar xzf docker.tgz
          mv docker/* /usr/local/bin
          rmdir docker
          : echo DOCKER_REGISTRY_URL=${GITHUB_SERVER_URL##*/} >> ${GITHUB_ENV}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: code.devcloud.soren.tools/platform/caddy
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=sha
            type=semver,pattern=v{{major}}.{{minor}}.{{patch}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=ref,event=tag
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: code.devcloud.soren.tools
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        env:
          ACTIONS_RUNTIME_TOKEN: ""
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          sbom: true
          provenance: true
